dict = {
    '2015' : ['Australian', 'Malaysian', 'Chinese', 'Bahrain', 'Spanish', 'Monaco', 'Canadian', 'Austrian', 'British', 'Hungarian', 'Belgian', 'Italian', 'Singapore', 'Japanese', 'Russian', 'United', 'Mexican', 'Brazilian', 'Abu'],
    '2014' : ['Australian', 'Malaysian', 'Bahrain', 'Chinese', 'Spanish', 'Monaco', 'Canadian', 'Austrian', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Singapore', 'Japanese', 'Russian', 'United', 'Brazilian', 'Abu'],
    '2013' : ['Australian', 'Malaysian', 'Chinese', 'Bahrain', 'Spanish', 'Monaco', 'Canadian', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Singapore', 'Korean', 'Japanese', 'Indian', 'Abu', 'United', 'Brazilian'],
    '2012' : ['Australian', 'Malaysian', 'Chinese', 'Bahrain', 'Spanish', 'Monaco', 'Canadian', 'European', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Singapore', 'Japanese', 'Korean', 'Abu', 'Indian', 'United', 'Brazilian'],
    '2011' : ['Australian', 'Malaysian', 'Chinese', 'Turkish', 'Spanish', 'Monaco', 'Canadian', 'European', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Singapore', 'Japanese', 'Korean', 'Indian', 'Abu', 'Brazilian'],
    '2010' : ['Bahrain', 'Australian', 'Malaysian', 'Chinese', 'Spanish', 'Monaco', 'Turkish', 'Canadian', 'European', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Singapore', 'Japanese', 'Korean', 'Brazilian', 'Abu'],
    '2009' : ['Australian', 'Malaysian', 'Chinese', 'Bahrain', 'Spanish', 'Monaco', 'Turkish', 'British', 'German', 'Hungarian', 'European', 'Belgian', 'Italian', 'Singapore', 'Japanese', 'Brazilian', 'Abu'],
    '2008' : ['Australian', 'Malaysian', 'Bahrain', 'Spanish', 'Turkish', 'Monaco', 'Canadian', 'French', 'British', 'German', 'Hungarian', 'European', 'Belgian', 'Italian', 'Singapore', 'Japanese', 'Chinese', 'Brazilian'],
    '2007' : ['Australian', 'Malaysian', 'Bahrain', 'Spanish', 'Monaco', 'Canadian', 'United', 'French', 'British', 'European', 'Hungarian', 'Turkish', 'Italian', 'Belgian', 'Japanese', 'Chinese', 'Brazilian'],
    '2006' : ['Bahrain', 'Malaysian', 'Australian', 'San', 'European', 'Spanish', 'Monaco', 'British', 'Canadian', 'United', 'French', 'German', 'Hungarian', 'Turkish', 'Italian', 'Chinese', 'Japanese', 'Brazilian'],
    '2005' : ['Australian', 'Malaysian', 'Bahrain', 'San', 'Spanish', 'Monaco', 'European', 'Canadian', 'United', 'French', 'British', 'German', 'Hungarian', 'Turkish', 'Italian', 'Belgian', 'Brazilian', 'Japanese', 'Chinese'],
    '2004' : ['Australian', 'Malaysian', 'Bahrain', 'San', 'Spanish', 'Monaco', 'European', 'Canadian', 'United', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Chinese', 'Japanese', 'Brazilian'],
    '2003' : ['Australian', 'Malaysian', 'Brazilian', 'San', 'Spanish', 'Austrian', 'Monaco', 'Canadian', 'European', 'French', 'British', 'German', 'Hungarian', 'Italian', 'United', 'Japanese'],
    '2002' : ['Australian', 'Malaysian', 'Brazilian', 'San', 'Spanish', 'Austrian', 'Monaco', 'Canadian', 'European', 'British', 'French', 'German', 'Hungarian', 'Belgian', 'Italian', 'United', 'Japanese'],
    '2001' : ['Australian', 'Malaysian', 'Brazilian', 'San', 'Spanish', 'Austrian', 'Monaco', 'Canadian', 'European', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'United', 'Japanese'],
    '2000' : ['Australian', 'Brazilian', 'San', 'British', 'Spanish', 'European', 'Monaco', 'Canadian', 'French', 'Austrian', 'German', 'Hungarian', 'Belgian', 'Italian', 'United', 'Japanese', 'Malaysian'],
    '1999' : ['Australian', 'Brazilian', 'San', 'Monaco', 'Spanish', 'Canadian', 'French', 'British', 'Austrian', 'German', 'Hungarian', 'Belgian', 'Italian', 'European', 'Malaysian', 'Japanese'],
    '1998' : ['Australian', 'Brazilian', 'Argentine', 'San', 'Spanish', 'Monaco', 'Canadian', 'French', 'British', 'Austrian', 'German', 'Hungarian', 'Belgian', 'Italian', 'Luxembourg', 'Japanese'],
    '1997' : ['Australian', 'Brazilian', 'Argentine', 'San', 'Monaco', 'Spanish', 'Canadian', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Austrian', 'Luxembourg', 'Japanese', 'European'],
    '1996' : ['Australian', 'Brazilian', 'Argentine', 'European', 'San', 'Monaco', 'Spanish', 'Canadian', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Portuguese', 'Japanese'],
    '1995' : ['Brazilian', 'Argentine', 'San', 'Spanish', 'Monaco', 'Canadian', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Portuguese', 'European', 'Pacific', 'Japanese', 'Australian'],
    '1994' : ['Brazilian', 'Pacific', 'San', 'Monaco', 'Spanish', 'Canadian', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Portuguese', 'European', 'Japanese', 'Australian'],
    '1993' : ['South', 'Brazilian', 'European', 'San', 'Spanish', 'Monaco', 'Canadian', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Portuguese', 'Japanese', 'Australian'],
    '1992' : ['South', 'Mexican', 'Brazilian', 'Spanish', 'San', 'Monaco', 'Canadian', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Portuguese', 'Japanese', 'Australian'],
    '1991' : ['United', 'Brazilian', 'San', 'Monaco', 'Canadian', 'Mexican', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Portuguese', 'Spanish', 'Japanese', 'Australian'],
    '1990' : ['United', 'Brazilian', 'San', 'Monaco', 'Canadian', 'Mexican', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Portuguese', 'Spanish', 'Japanese', 'Australian'],
    '1989' : ['Brazilian', 'San', 'Monaco', 'Mexican', 'United', 'Canadian', 'French', 'British', 'German', 'Hungarian', 'Belgian', 'Italian', 'Portuguese', 'Spanish', 'Japanese', 'Australian']
    }
